#!/usr/bin/env ansible-playbook
---

- hosts: all
  gather_facts: False
  user: root
  tasks:
    - name: screenrc - apt
      apt: { name: screen }

- hosts: all
  gather_facts: True

  vars_prompt:
    - name: screen_password
      prompt: screen password
      private: yes

  roles:
    - role: self
      user: thy
      dir: ~/.thy
      files: [ local.screen, remote.screen ]
      file: local.screen
      link: .screenrc
      salt: 42
      password: |
        {{ screen_password is defined and screen_password != '' }}
